// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: movies.proto

package movies;

public final class Movies {
  private Movies() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MovieOrBuilder extends
      // @@protoc_insertion_point(interface_extends:movies.Movie)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string title = 1;</code>
     */
    java.lang.String getTitle();
    /**
     * <code>string title = 1;</code>
     */
    com.google.protobuf.ByteString
        getTitleBytes();

    /**
     * <code>int32 year = 2;</code>
     */
    int getYear();

    /**
     * <code>string director = 3;</code>
     */
    java.lang.String getDirector();
    /**
     * <code>string director = 3;</code>
     */
    com.google.protobuf.ByteString
        getDirectorBytes();

    /**
     * <code>repeated string actor = 4;</code>
     */
    java.util.List<java.lang.String>
        getActorList();
    /**
     * <code>repeated string actor = 4;</code>
     */
    int getActorCount();
    /**
     * <code>repeated string actor = 4;</code>
     */
    java.lang.String getActor(int index);
    /**
     * <code>repeated string actor = 4;</code>
     */
    com.google.protobuf.ByteString
        getActorBytes(int index);
  }
  /**
   * Protobuf type {@code movies.Movie}
   */
  public  static final class Movie extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:movies.Movie)
      MovieOrBuilder {
    // Use Movie.newBuilder() to construct.
    private Movie(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Movie() {
      title_ = "";
      year_ = 0;
      director_ = "";
      actor_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Movie(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              title_ = s;
              break;
            }
            case 16: {

              year_ = input.readInt32();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              director_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                actor_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000008;
              }
              actor_.add(s);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          actor_ = actor_.getUnmodifiableView();
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return movies.Movies.internal_static_movies_Movie_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return movies.Movies.internal_static_movies_Movie_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              movies.Movies.Movie.class, movies.Movies.Movie.Builder.class);
    }

    private int bitField0_;
    public static final int TITLE_FIELD_NUMBER = 1;
    private volatile java.lang.Object title_;
    /**
     * <code>string title = 1;</code>
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        title_ = s;
        return s;
      }
    }
    /**
     * <code>string title = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int YEAR_FIELD_NUMBER = 2;
    private int year_;
    /**
     * <code>int32 year = 2;</code>
     */
    public int getYear() {
      return year_;
    }

    public static final int DIRECTOR_FIELD_NUMBER = 3;
    private volatile java.lang.Object director_;
    /**
     * <code>string director = 3;</code>
     */
    public java.lang.String getDirector() {
      java.lang.Object ref = director_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        director_ = s;
        return s;
      }
    }
    /**
     * <code>string director = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDirectorBytes() {
      java.lang.Object ref = director_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        director_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ACTOR_FIELD_NUMBER = 4;
    private com.google.protobuf.LazyStringList actor_;
    /**
     * <code>repeated string actor = 4;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getActorList() {
      return actor_;
    }
    /**
     * <code>repeated string actor = 4;</code>
     */
    public int getActorCount() {
      return actor_.size();
    }
    /**
     * <code>repeated string actor = 4;</code>
     */
    public java.lang.String getActor(int index) {
      return actor_.get(index);
    }
    /**
     * <code>repeated string actor = 4;</code>
     */
    public com.google.protobuf.ByteString
        getActorBytes(int index) {
      return actor_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getTitleBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, title_);
      }
      if (year_ != 0) {
        output.writeInt32(2, year_);
      }
      if (!getDirectorBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, director_);
      }
      for (int i = 0; i < actor_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, actor_.getRaw(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getTitleBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, title_);
      }
      if (year_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, year_);
      }
      if (!getDirectorBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, director_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < actor_.size(); i++) {
          dataSize += computeStringSizeNoTag(actor_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getActorList().size();
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof movies.Movies.Movie)) {
        return super.equals(obj);
      }
      movies.Movies.Movie other = (movies.Movies.Movie) obj;

      boolean result = true;
      result = result && getTitle()
          .equals(other.getTitle());
      result = result && (getYear()
          == other.getYear());
      result = result && getDirector()
          .equals(other.getDirector());
      result = result && getActorList()
          .equals(other.getActorList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TITLE_FIELD_NUMBER;
      hash = (53 * hash) + getTitle().hashCode();
      hash = (37 * hash) + YEAR_FIELD_NUMBER;
      hash = (53 * hash) + getYear();
      hash = (37 * hash) + DIRECTOR_FIELD_NUMBER;
      hash = (53 * hash) + getDirector().hashCode();
      if (getActorCount() > 0) {
        hash = (37 * hash) + ACTOR_FIELD_NUMBER;
        hash = (53 * hash) + getActorList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static movies.Movies.Movie parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static movies.Movies.Movie parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static movies.Movies.Movie parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static movies.Movies.Movie parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static movies.Movies.Movie parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static movies.Movies.Movie parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static movies.Movies.Movie parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static movies.Movies.Movie parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static movies.Movies.Movie parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static movies.Movies.Movie parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(movies.Movies.Movie prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code movies.Movie}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:movies.Movie)
        movies.Movies.MovieOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return movies.Movies.internal_static_movies_Movie_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return movies.Movies.internal_static_movies_Movie_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                movies.Movies.Movie.class, movies.Movies.Movie.Builder.class);
      }

      // Construct using movies.Movies.Movie.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        title_ = "";

        year_ = 0;

        director_ = "";

        actor_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return movies.Movies.internal_static_movies_Movie_descriptor;
      }

      public movies.Movies.Movie getDefaultInstanceForType() {
        return movies.Movies.Movie.getDefaultInstance();
      }

      public movies.Movies.Movie build() {
        movies.Movies.Movie result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public movies.Movies.Movie buildPartial() {
        movies.Movies.Movie result = new movies.Movies.Movie(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.title_ = title_;
        result.year_ = year_;
        result.director_ = director_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          actor_ = actor_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.actor_ = actor_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof movies.Movies.Movie) {
          return mergeFrom((movies.Movies.Movie)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(movies.Movies.Movie other) {
        if (other == movies.Movies.Movie.getDefaultInstance()) return this;
        if (!other.getTitle().isEmpty()) {
          title_ = other.title_;
          onChanged();
        }
        if (other.getYear() != 0) {
          setYear(other.getYear());
        }
        if (!other.getDirector().isEmpty()) {
          director_ = other.director_;
          onChanged();
        }
        if (!other.actor_.isEmpty()) {
          if (actor_.isEmpty()) {
            actor_ = other.actor_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureActorIsMutable();
            actor_.addAll(other.actor_);
          }
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        movies.Movies.Movie parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (movies.Movies.Movie) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object title_ = "";
      /**
       * <code>string title = 1;</code>
       */
      public java.lang.String getTitle() {
        java.lang.Object ref = title_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          title_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string title = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        java.lang.Object ref = title_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string title = 1;</code>
       */
      public Builder setTitle(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        title_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string title = 1;</code>
       */
      public Builder clearTitle() {
        
        title_ = getDefaultInstance().getTitle();
        onChanged();
        return this;
      }
      /**
       * <code>string title = 1;</code>
       */
      public Builder setTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        title_ = value;
        onChanged();
        return this;
      }

      private int year_ ;
      /**
       * <code>int32 year = 2;</code>
       */
      public int getYear() {
        return year_;
      }
      /**
       * <code>int32 year = 2;</code>
       */
      public Builder setYear(int value) {
        
        year_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 year = 2;</code>
       */
      public Builder clearYear() {
        
        year_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object director_ = "";
      /**
       * <code>string director = 3;</code>
       */
      public java.lang.String getDirector() {
        java.lang.Object ref = director_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          director_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string director = 3;</code>
       */
      public com.google.protobuf.ByteString
          getDirectorBytes() {
        java.lang.Object ref = director_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          director_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string director = 3;</code>
       */
      public Builder setDirector(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        director_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string director = 3;</code>
       */
      public Builder clearDirector() {
        
        director_ = getDefaultInstance().getDirector();
        onChanged();
        return this;
      }
      /**
       * <code>string director = 3;</code>
       */
      public Builder setDirectorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        director_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList actor_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureActorIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          actor_ = new com.google.protobuf.LazyStringArrayList(actor_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated string actor = 4;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getActorList() {
        return actor_.getUnmodifiableView();
      }
      /**
       * <code>repeated string actor = 4;</code>
       */
      public int getActorCount() {
        return actor_.size();
      }
      /**
       * <code>repeated string actor = 4;</code>
       */
      public java.lang.String getActor(int index) {
        return actor_.get(index);
      }
      /**
       * <code>repeated string actor = 4;</code>
       */
      public com.google.protobuf.ByteString
          getActorBytes(int index) {
        return actor_.getByteString(index);
      }
      /**
       * <code>repeated string actor = 4;</code>
       */
      public Builder setActor(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureActorIsMutable();
        actor_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string actor = 4;</code>
       */
      public Builder addActor(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureActorIsMutable();
        actor_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string actor = 4;</code>
       */
      public Builder addAllActor(
          java.lang.Iterable<java.lang.String> values) {
        ensureActorIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, actor_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string actor = 4;</code>
       */
      public Builder clearActor() {
        actor_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string actor = 4;</code>
       */
      public Builder addActorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureActorIsMutable();
        actor_.add(value);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:movies.Movie)
    }

    // @@protoc_insertion_point(class_scope:movies.Movie)
    private static final movies.Movies.Movie DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new movies.Movies.Movie();
    }

    public static movies.Movies.Movie getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Movie>
        PARSER = new com.google.protobuf.AbstractParser<Movie>() {
      public Movie parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Movie(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Movie> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Movie> getParserForType() {
      return PARSER;
    }

    public movies.Movies.Movie getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MovieIdOrBuilder extends
      // @@protoc_insertion_point(interface_extends:movies.MovieId)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     */
    int getId();
  }
  /**
   * Protobuf type {@code movies.MovieId}
   */
  public  static final class MovieId extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:movies.MovieId)
      MovieIdOrBuilder {
    // Use MovieId.newBuilder() to construct.
    private MovieId(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MovieId() {
      id_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private MovieId(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              id_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return movies.Movies.internal_static_movies_MovieId_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return movies.Movies.internal_static_movies_MovieId_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              movies.Movies.MovieId.class, movies.Movies.MovieId.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof movies.Movies.MovieId)) {
        return super.equals(obj);
      }
      movies.Movies.MovieId other = (movies.Movies.MovieId) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static movies.Movies.MovieId parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static movies.Movies.MovieId parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static movies.Movies.MovieId parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static movies.Movies.MovieId parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static movies.Movies.MovieId parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static movies.Movies.MovieId parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static movies.Movies.MovieId parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static movies.Movies.MovieId parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static movies.Movies.MovieId parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static movies.Movies.MovieId parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(movies.Movies.MovieId prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code movies.MovieId}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:movies.MovieId)
        movies.Movies.MovieIdOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return movies.Movies.internal_static_movies_MovieId_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return movies.Movies.internal_static_movies_MovieId_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                movies.Movies.MovieId.class, movies.Movies.MovieId.Builder.class);
      }

      // Construct using movies.Movies.MovieId.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return movies.Movies.internal_static_movies_MovieId_descriptor;
      }

      public movies.Movies.MovieId getDefaultInstanceForType() {
        return movies.Movies.MovieId.getDefaultInstance();
      }

      public movies.Movies.MovieId build() {
        movies.Movies.MovieId result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public movies.Movies.MovieId buildPartial() {
        movies.Movies.MovieId result = new movies.Movies.MovieId(this);
        result.id_ = id_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof movies.Movies.MovieId) {
          return mergeFrom((movies.Movies.MovieId)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(movies.Movies.MovieId other) {
        if (other == movies.Movies.MovieId.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        movies.Movies.MovieId parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (movies.Movies.MovieId) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:movies.MovieId)
    }

    // @@protoc_insertion_point(class_scope:movies.MovieId)
    private static final movies.Movies.MovieId DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new movies.Movies.MovieId();
    }

    public static movies.Movies.MovieId getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MovieId>
        PARSER = new com.google.protobuf.AbstractParser<MovieId>() {
      public MovieId parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new MovieId(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MovieId> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MovieId> getParserForType() {
      return PARSER;
    }

    public movies.Movies.MovieId getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MovieListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:movies.MovieList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .movies.Movie movie = 1;</code>
     */
    java.util.List<movies.Movies.Movie> 
        getMovieList();
    /**
     * <code>repeated .movies.Movie movie = 1;</code>
     */
    movies.Movies.Movie getMovie(int index);
    /**
     * <code>repeated .movies.Movie movie = 1;</code>
     */
    int getMovieCount();
    /**
     * <code>repeated .movies.Movie movie = 1;</code>
     */
    java.util.List<? extends movies.Movies.MovieOrBuilder> 
        getMovieOrBuilderList();
    /**
     * <code>repeated .movies.Movie movie = 1;</code>
     */
    movies.Movies.MovieOrBuilder getMovieOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code movies.MovieList}
   */
  public  static final class MovieList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:movies.MovieList)
      MovieListOrBuilder {
    // Use MovieList.newBuilder() to construct.
    private MovieList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MovieList() {
      movie_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private MovieList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                movie_ = new java.util.ArrayList<movies.Movies.Movie>();
                mutable_bitField0_ |= 0x00000001;
              }
              movie_.add(
                  input.readMessage(movies.Movies.Movie.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          movie_ = java.util.Collections.unmodifiableList(movie_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return movies.Movies.internal_static_movies_MovieList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return movies.Movies.internal_static_movies_MovieList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              movies.Movies.MovieList.class, movies.Movies.MovieList.Builder.class);
    }

    public static final int MOVIE_FIELD_NUMBER = 1;
    private java.util.List<movies.Movies.Movie> movie_;
    /**
     * <code>repeated .movies.Movie movie = 1;</code>
     */
    public java.util.List<movies.Movies.Movie> getMovieList() {
      return movie_;
    }
    /**
     * <code>repeated .movies.Movie movie = 1;</code>
     */
    public java.util.List<? extends movies.Movies.MovieOrBuilder> 
        getMovieOrBuilderList() {
      return movie_;
    }
    /**
     * <code>repeated .movies.Movie movie = 1;</code>
     */
    public int getMovieCount() {
      return movie_.size();
    }
    /**
     * <code>repeated .movies.Movie movie = 1;</code>
     */
    public movies.Movies.Movie getMovie(int index) {
      return movie_.get(index);
    }
    /**
     * <code>repeated .movies.Movie movie = 1;</code>
     */
    public movies.Movies.MovieOrBuilder getMovieOrBuilder(
        int index) {
      return movie_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < movie_.size(); i++) {
        output.writeMessage(1, movie_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < movie_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, movie_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof movies.Movies.MovieList)) {
        return super.equals(obj);
      }
      movies.Movies.MovieList other = (movies.Movies.MovieList) obj;

      boolean result = true;
      result = result && getMovieList()
          .equals(other.getMovieList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getMovieCount() > 0) {
        hash = (37 * hash) + MOVIE_FIELD_NUMBER;
        hash = (53 * hash) + getMovieList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static movies.Movies.MovieList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static movies.Movies.MovieList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static movies.Movies.MovieList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static movies.Movies.MovieList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static movies.Movies.MovieList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static movies.Movies.MovieList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static movies.Movies.MovieList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static movies.Movies.MovieList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static movies.Movies.MovieList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static movies.Movies.MovieList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(movies.Movies.MovieList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code movies.MovieList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:movies.MovieList)
        movies.Movies.MovieListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return movies.Movies.internal_static_movies_MovieList_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return movies.Movies.internal_static_movies_MovieList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                movies.Movies.MovieList.class, movies.Movies.MovieList.Builder.class);
      }

      // Construct using movies.Movies.MovieList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getMovieFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (movieBuilder_ == null) {
          movie_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          movieBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return movies.Movies.internal_static_movies_MovieList_descriptor;
      }

      public movies.Movies.MovieList getDefaultInstanceForType() {
        return movies.Movies.MovieList.getDefaultInstance();
      }

      public movies.Movies.MovieList build() {
        movies.Movies.MovieList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public movies.Movies.MovieList buildPartial() {
        movies.Movies.MovieList result = new movies.Movies.MovieList(this);
        int from_bitField0_ = bitField0_;
        if (movieBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            movie_ = java.util.Collections.unmodifiableList(movie_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.movie_ = movie_;
        } else {
          result.movie_ = movieBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof movies.Movies.MovieList) {
          return mergeFrom((movies.Movies.MovieList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(movies.Movies.MovieList other) {
        if (other == movies.Movies.MovieList.getDefaultInstance()) return this;
        if (movieBuilder_ == null) {
          if (!other.movie_.isEmpty()) {
            if (movie_.isEmpty()) {
              movie_ = other.movie_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureMovieIsMutable();
              movie_.addAll(other.movie_);
            }
            onChanged();
          }
        } else {
          if (!other.movie_.isEmpty()) {
            if (movieBuilder_.isEmpty()) {
              movieBuilder_.dispose();
              movieBuilder_ = null;
              movie_ = other.movie_;
              bitField0_ = (bitField0_ & ~0x00000001);
              movieBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getMovieFieldBuilder() : null;
            } else {
              movieBuilder_.addAllMessages(other.movie_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        movies.Movies.MovieList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (movies.Movies.MovieList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<movies.Movies.Movie> movie_ =
        java.util.Collections.emptyList();
      private void ensureMovieIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          movie_ = new java.util.ArrayList<movies.Movies.Movie>(movie_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          movies.Movies.Movie, movies.Movies.Movie.Builder, movies.Movies.MovieOrBuilder> movieBuilder_;

      /**
       * <code>repeated .movies.Movie movie = 1;</code>
       */
      public java.util.List<movies.Movies.Movie> getMovieList() {
        if (movieBuilder_ == null) {
          return java.util.Collections.unmodifiableList(movie_);
        } else {
          return movieBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .movies.Movie movie = 1;</code>
       */
      public int getMovieCount() {
        if (movieBuilder_ == null) {
          return movie_.size();
        } else {
          return movieBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .movies.Movie movie = 1;</code>
       */
      public movies.Movies.Movie getMovie(int index) {
        if (movieBuilder_ == null) {
          return movie_.get(index);
        } else {
          return movieBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .movies.Movie movie = 1;</code>
       */
      public Builder setMovie(
          int index, movies.Movies.Movie value) {
        if (movieBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMovieIsMutable();
          movie_.set(index, value);
          onChanged();
        } else {
          movieBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .movies.Movie movie = 1;</code>
       */
      public Builder setMovie(
          int index, movies.Movies.Movie.Builder builderForValue) {
        if (movieBuilder_ == null) {
          ensureMovieIsMutable();
          movie_.set(index, builderForValue.build());
          onChanged();
        } else {
          movieBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .movies.Movie movie = 1;</code>
       */
      public Builder addMovie(movies.Movies.Movie value) {
        if (movieBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMovieIsMutable();
          movie_.add(value);
          onChanged();
        } else {
          movieBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .movies.Movie movie = 1;</code>
       */
      public Builder addMovie(
          int index, movies.Movies.Movie value) {
        if (movieBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMovieIsMutable();
          movie_.add(index, value);
          onChanged();
        } else {
          movieBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .movies.Movie movie = 1;</code>
       */
      public Builder addMovie(
          movies.Movies.Movie.Builder builderForValue) {
        if (movieBuilder_ == null) {
          ensureMovieIsMutable();
          movie_.add(builderForValue.build());
          onChanged();
        } else {
          movieBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .movies.Movie movie = 1;</code>
       */
      public Builder addMovie(
          int index, movies.Movies.Movie.Builder builderForValue) {
        if (movieBuilder_ == null) {
          ensureMovieIsMutable();
          movie_.add(index, builderForValue.build());
          onChanged();
        } else {
          movieBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .movies.Movie movie = 1;</code>
       */
      public Builder addAllMovie(
          java.lang.Iterable<? extends movies.Movies.Movie> values) {
        if (movieBuilder_ == null) {
          ensureMovieIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, movie_);
          onChanged();
        } else {
          movieBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .movies.Movie movie = 1;</code>
       */
      public Builder clearMovie() {
        if (movieBuilder_ == null) {
          movie_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          movieBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .movies.Movie movie = 1;</code>
       */
      public Builder removeMovie(int index) {
        if (movieBuilder_ == null) {
          ensureMovieIsMutable();
          movie_.remove(index);
          onChanged();
        } else {
          movieBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .movies.Movie movie = 1;</code>
       */
      public movies.Movies.Movie.Builder getMovieBuilder(
          int index) {
        return getMovieFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .movies.Movie movie = 1;</code>
       */
      public movies.Movies.MovieOrBuilder getMovieOrBuilder(
          int index) {
        if (movieBuilder_ == null) {
          return movie_.get(index);  } else {
          return movieBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .movies.Movie movie = 1;</code>
       */
      public java.util.List<? extends movies.Movies.MovieOrBuilder> 
           getMovieOrBuilderList() {
        if (movieBuilder_ != null) {
          return movieBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(movie_);
        }
      }
      /**
       * <code>repeated .movies.Movie movie = 1;</code>
       */
      public movies.Movies.Movie.Builder addMovieBuilder() {
        return getMovieFieldBuilder().addBuilder(
            movies.Movies.Movie.getDefaultInstance());
      }
      /**
       * <code>repeated .movies.Movie movie = 1;</code>
       */
      public movies.Movies.Movie.Builder addMovieBuilder(
          int index) {
        return getMovieFieldBuilder().addBuilder(
            index, movies.Movies.Movie.getDefaultInstance());
      }
      /**
       * <code>repeated .movies.Movie movie = 1;</code>
       */
      public java.util.List<movies.Movies.Movie.Builder> 
           getMovieBuilderList() {
        return getMovieFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          movies.Movies.Movie, movies.Movies.Movie.Builder, movies.Movies.MovieOrBuilder> 
          getMovieFieldBuilder() {
        if (movieBuilder_ == null) {
          movieBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              movies.Movies.Movie, movies.Movies.Movie.Builder, movies.Movies.MovieOrBuilder>(
                  movie_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          movie_ = null;
        }
        return movieBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:movies.MovieList)
    }

    // @@protoc_insertion_point(class_scope:movies.MovieList)
    private static final movies.Movies.MovieList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new movies.Movies.MovieList();
    }

    public static movies.Movies.MovieList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MovieList>
        PARSER = new com.google.protobuf.AbstractParser<MovieList>() {
      public MovieList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new MovieList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MovieList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MovieList> getParserForType() {
      return PARSER;
    }

    public movies.Movies.MovieList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MovieIdListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:movies.MovieIdList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated int32 id = 1;</code>
     */
    java.util.List<java.lang.Integer> getIdList();
    /**
     * <code>repeated int32 id = 1;</code>
     */
    int getIdCount();
    /**
     * <code>repeated int32 id = 1;</code>
     */
    int getId(int index);
  }
  /**
   * Protobuf type {@code movies.MovieIdList}
   */
  public  static final class MovieIdList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:movies.MovieIdList)
      MovieIdListOrBuilder {
    // Use MovieIdList.newBuilder() to construct.
    private MovieIdList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MovieIdList() {
      id_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private MovieIdList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                id_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              id_.add(input.readInt32());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
                id_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                id_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          id_ = java.util.Collections.unmodifiableList(id_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return movies.Movies.internal_static_movies_MovieIdList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return movies.Movies.internal_static_movies_MovieIdList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              movies.Movies.MovieIdList.class, movies.Movies.MovieIdList.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private java.util.List<java.lang.Integer> id_;
    /**
     * <code>repeated int32 id = 1;</code>
     */
    public java.util.List<java.lang.Integer>
        getIdList() {
      return id_;
    }
    /**
     * <code>repeated int32 id = 1;</code>
     */
    public int getIdCount() {
      return id_.size();
    }
    /**
     * <code>repeated int32 id = 1;</code>
     */
    public int getId(int index) {
      return id_.get(index);
    }
    private int idMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (getIdList().size() > 0) {
        output.writeUInt32NoTag(10);
        output.writeUInt32NoTag(idMemoizedSerializedSize);
      }
      for (int i = 0; i < id_.size(); i++) {
        output.writeInt32NoTag(id_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < id_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(id_.get(i));
        }
        size += dataSize;
        if (!getIdList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        idMemoizedSerializedSize = dataSize;
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof movies.Movies.MovieIdList)) {
        return super.equals(obj);
      }
      movies.Movies.MovieIdList other = (movies.Movies.MovieIdList) obj;

      boolean result = true;
      result = result && getIdList()
          .equals(other.getIdList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getIdCount() > 0) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getIdList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static movies.Movies.MovieIdList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static movies.Movies.MovieIdList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static movies.Movies.MovieIdList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static movies.Movies.MovieIdList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static movies.Movies.MovieIdList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static movies.Movies.MovieIdList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static movies.Movies.MovieIdList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static movies.Movies.MovieIdList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static movies.Movies.MovieIdList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static movies.Movies.MovieIdList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(movies.Movies.MovieIdList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code movies.MovieIdList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:movies.MovieIdList)
        movies.Movies.MovieIdListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return movies.Movies.internal_static_movies_MovieIdList_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return movies.Movies.internal_static_movies_MovieIdList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                movies.Movies.MovieIdList.class, movies.Movies.MovieIdList.Builder.class);
      }

      // Construct using movies.Movies.MovieIdList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return movies.Movies.internal_static_movies_MovieIdList_descriptor;
      }

      public movies.Movies.MovieIdList getDefaultInstanceForType() {
        return movies.Movies.MovieIdList.getDefaultInstance();
      }

      public movies.Movies.MovieIdList build() {
        movies.Movies.MovieIdList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public movies.Movies.MovieIdList buildPartial() {
        movies.Movies.MovieIdList result = new movies.Movies.MovieIdList(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          id_ = java.util.Collections.unmodifiableList(id_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.id_ = id_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof movies.Movies.MovieIdList) {
          return mergeFrom((movies.Movies.MovieIdList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(movies.Movies.MovieIdList other) {
        if (other == movies.Movies.MovieIdList.getDefaultInstance()) return this;
        if (!other.id_.isEmpty()) {
          if (id_.isEmpty()) {
            id_ = other.id_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureIdIsMutable();
            id_.addAll(other.id_);
          }
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        movies.Movies.MovieIdList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (movies.Movies.MovieIdList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<java.lang.Integer> id_ = java.util.Collections.emptyList();
      private void ensureIdIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          id_ = new java.util.ArrayList<java.lang.Integer>(id_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated int32 id = 1;</code>
       */
      public java.util.List<java.lang.Integer>
          getIdList() {
        return java.util.Collections.unmodifiableList(id_);
      }
      /**
       * <code>repeated int32 id = 1;</code>
       */
      public int getIdCount() {
        return id_.size();
      }
      /**
       * <code>repeated int32 id = 1;</code>
       */
      public int getId(int index) {
        return id_.get(index);
      }
      /**
       * <code>repeated int32 id = 1;</code>
       */
      public Builder setId(
          int index, int value) {
        ensureIdIsMutable();
        id_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 id = 1;</code>
       */
      public Builder addId(int value) {
        ensureIdIsMutable();
        id_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 id = 1;</code>
       */
      public Builder addAllId(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureIdIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, id_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 id = 1;</code>
       */
      public Builder clearId() {
        id_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:movies.MovieIdList)
    }

    // @@protoc_insertion_point(class_scope:movies.MovieIdList)
    private static final movies.Movies.MovieIdList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new movies.Movies.MovieIdList();
    }

    public static movies.Movies.MovieIdList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MovieIdList>
        PARSER = new com.google.protobuf.AbstractParser<MovieIdList>() {
      public MovieIdList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new MovieIdList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MovieIdList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MovieIdList> getParserForType() {
      return PARSER;
    }

    public movies.Movies.MovieIdList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_movies_Movie_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_movies_Movie_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_movies_MovieId_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_movies_MovieId_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_movies_MovieList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_movies_MovieList_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_movies_MovieIdList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_movies_MovieIdList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014movies.proto\022\006movies\"E\n\005Movie\022\r\n\005title" +
      "\030\001 \001(\t\022\014\n\004year\030\002 \001(\005\022\020\n\010director\030\003 \001(\t\022\r" +
      "\n\005actor\030\004 \003(\t\"\025\n\007MovieId\022\n\n\002id\030\001 \001(\005\")\n\t" +
      "MovieList\022\034\n\005movie\030\001 \003(\0132\r.movies.Movie\"" +
      "\031\n\013MovieIdList\022\n\n\002id\030\001 \003(\005b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_movies_Movie_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_movies_Movie_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_movies_Movie_descriptor,
        new java.lang.String[] { "Title", "Year", "Director", "Actor", });
    internal_static_movies_MovieId_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_movies_MovieId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_movies_MovieId_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_movies_MovieList_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_movies_MovieList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_movies_MovieList_descriptor,
        new java.lang.String[] { "Movie", });
    internal_static_movies_MovieIdList_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_movies_MovieIdList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_movies_MovieIdList_descriptor,
        new java.lang.String[] { "Id", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
